"""
Worker 49: Dark Web & OSINT Intelligence (استخبارات الدارك ويب والمصادر المفتوحة)

This agent periodically scans configured threat intel feeds, 
pastebin dumps, and open-source intelligence sources for mentions 
of the company's domain, VIP emails, or specific keywords.
"""

import time
import logging
import os
import json
from typing import Any, Dict, List, Optional
from datetime import datetime, timezone

from shared.base_agent import BaseAgent
from shared.config import SOCConfig
from shared.alerter import Severity

logger = logging.getLogger("soc.worker.w49_darkweb_osint")

class DarkWebOSINTAgent(BaseAgent):
    def __init__(self, config: Optional[SOCConfig] = None) -> None:
        super().__init__(
            name="w49_darkweb_osint",
            description="Monitors OSINT & simulated dark web feeds for corporate leaks.",
            interval_seconds=3600, # Run once an hour
            config=config,
        )
        self.keywords = ["khandaq", "khandaq.local", "vip@khandaq.com"]
        self.intel_dir = "/app/data/intel_feeds"

    def collect(self) -> List[Dict[str, Any]]:
        # Read from the ephemeral intel bubble's local volume
        logger.info(f"Scanning local OSINT feeds generated by Ephemeral Bubble in {self.intel_dir}...")
        findings = []
        
        filepath = os.path.join(self.intel_dir, "darkweb_osint.txt")
        if os.path.exists(filepath):
            with open(filepath, "r") as f:
                content = f.read()
                # Check for our keywords in the raw dump
                for kw in self.keywords:
                    if kw in content.lower():
                        findings.append({
                            "source": "Local_Intel_Volume",
                            "keyword": kw,
                            "content": f"Found mention of {kw} in latest OSINT dump.",
                            "timestamp": time.time()
                        })
        else:
            logger.debug(f"Feed file not found: {filepath}. Waiting for bubble to run.")
            
        return findings

    def analyze(self, data: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        findings = []
        for item in data:
            if any(kw in item.get("content", "").lower() for kw in self.keywords):
                findings.append({
                    "type": "DATA_LEAK_DETECTED",
                    "severity": Severity.CRITICAL,
                    "host": "External (DarkWeb)",
                    "details": f"Corporate keyword '{item['keyword']}' found in {item['source']}. Content: {item['content']}",
                    "response": "FORCE_PASSWORD_RESET"
                })
        return findings

    def decide(self, findings: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        actions = []
        for finding in findings:
            actions.append({
                "action": "escalate",
                "finding": finding
            })
        return actions

    def act(self, actions: List[Dict[str, Any]]) -> Dict[str, Any]:
        results = {"escalated": 0}
        for action in actions:
            if action["action"] == "escalate":
                self.escalate_to_supervisor(
                    supervisor_channel="soc:detection-supervisor",
                    finding=action["finding"]
                )
                results["escalated"] += 1
                logger.warning(f"OSINT Leak Escalated: {action['finding']['details']}")
        return results

if __name__ == "__main__":
    import sys
    logging.basicConfig(level=logging.INFO, stream=sys.stdout)
    agent = DarkWebOSINTAgent()
    agent.run_loop()
