"""
SOC Platform - Prometheus Metrics Exporter
مصدّر مقاييس بروميثيوس

Provides a lightweight HTTP server exposing agent-level metrics:
- Events processed
- Alerts generated
- Errors encountered
- Last run timestamp
- Run duration
"""

from __future__ import annotations

import logging
import threading
from typing import Optional

from prometheus_client import (
    CollectorRegistry,
    Counter,
    Gauge,
    Histogram,
    start_http_server,
)

from .config import SOCConfig

logger = logging.getLogger("soc.metrics")


# ---------------------------------------------------------------------------
# Global registry (shared by all agents in the same process)
# السجل العالمي (مشترك بين جميع الوكلاء في نفس العملية)
# ---------------------------------------------------------------------------

REGISTRY = CollectorRegistry()

# -- Counters / عدادات --
EVENTS_PROCESSED = Counter(
    "agent_events_processed_total",
    "Total events processed by the agent",
    ["agent_name"],
    registry=REGISTRY,
)

ALERTS_GENERATED = Counter(
    "agent_alerts_generated_total",
    "Total alerts generated by the agent",
    ["agent_name", "severity"],
    registry=REGISTRY,
)

ERRORS_TOTAL = Counter(
    "agent_errors_total",
    "Total errors encountered by the agent",
    ["agent_name", "error_type"],
    registry=REGISTRY,
)

# -- Gauges / مقاييس --
LAST_RUN_TIMESTAMP = Gauge(
    "agent_last_run_timestamp",
    "Unix timestamp of the agent's last successful run",
    ["agent_name"],
    registry=REGISTRY,
)

# -- Histograms / رسوم بيانية --
RUN_DURATION = Histogram(
    "agent_run_duration_seconds",
    "Duration of each agent run cycle in seconds",
    ["agent_name"],
    buckets=(0.1, 0.5, 1, 2, 5, 10, 30, 60, 120, 300),
    registry=REGISTRY,
)

# ---------------------------------------------------------------------------
# LLM Metrics / مقاييس نماذج الذكاء الاصطناعي
# ---------------------------------------------------------------------------

LLM_REQUEST_DURATION = Histogram(
    "llm_request_duration_seconds",
    "Duration of LLM inference requests",
    ["model", "role"],
    buckets=(0.5, 1, 2, 5, 10, 30, 60, 120),
    registry=REGISTRY,
)

LLM_REQUESTS_TOTAL = Counter(
    "llm_requests_total",
    "Total LLM requests made",
    ["model", "role", "status"],
    registry=REGISTRY,
)

LLM_TOKENS_USED = Counter(
    "llm_tokens_used_total",
    "Total tokens used in LLM requests (prompt + completion)",
    ["model", "role", "token_type"],
    registry=REGISTRY,
)

# ---------------------------------------------------------------------------
# Redis Queue Metrics / مقاييس طابور ريدس
# ---------------------------------------------------------------------------

REDIS_QUEUE_DEPTH = Gauge(
    "redis_queue_depth",
    "Number of items in Redis hash queues",
    ["queue_name"],
    registry=REGISTRY,
)

REDIS_PUBLISH_TOTAL = Counter(
    "redis_publish_total",
    "Total messages published to Redis channels",
    ["channel"],
    registry=REGISTRY,
)


# ---------------------------------------------------------------------------
# Metrics Server Management / إدارة خادم المقاييس
# ---------------------------------------------------------------------------

_server_started = False
_server_lock = threading.Lock()


def start_metrics_server(config: Optional[SOCConfig] = None) -> None:
    """
    Start the Prometheus metrics HTTP server (once per process).

    The server runs in a daemon thread and survives until process exit.
    Calling this multiple times is safe — it's idempotent.

    Args:
        config: SOCConfig instance. Falls back to singleton if not provided.
    """
    global _server_started

    cfg = (config or SOCConfig.get_instance()).metrics

    if not cfg.enabled:
        logger.info("Prometheus metrics server disabled by config")
        return

    with _server_lock:
        if _server_started:
            return
        try:
            start_http_server(cfg.port, registry=REGISTRY)
            _server_started = True
            logger.info(
                "Prometheus metrics server started on port %d", cfg.port
            )
        except OSError as exc:
            logger.error(
                "Failed to start metrics server on port %d: %s", cfg.port, exc
            )


# ---------------------------------------------------------------------------
# Convenience helpers for agents / دوال مساعدة للوكلاء
# ---------------------------------------------------------------------------

class AgentMetrics:
    """
    Per-agent metrics wrapper for convenient access.
    مجمّع مقاييس لكل وكيل لسهولة الاستخدام

    Usage:
        metrics = AgentMetrics("w37_brute_force")
        metrics.inc_events(10)
        metrics.inc_alerts("HIGH")
        metrics.observe_duration(2.5)
    """

    def __init__(self, agent_name: str) -> None:
        self.agent_name = agent_name

    def inc_events(self, count: int = 1) -> None:
        """Increment events processed counter."""
        EVENTS_PROCESSED.labels(agent_name=self.agent_name).inc(count)

    def inc_alerts(self, severity: str, count: int = 1) -> None:
        """Increment alerts generated counter."""
        ALERTS_GENERATED.labels(
            agent_name=self.agent_name, severity=severity
        ).inc(count)

    def inc_errors(self, error_type: str = "general", count: int = 1) -> None:
        """Increment error counter."""
        ERRORS_TOTAL.labels(
            agent_name=self.agent_name, error_type=error_type
        ).inc(count)

    def set_last_run(self, timestamp: Optional[float] = None) -> None:
        """Set the last run timestamp (defaults to now)."""
        import time
        LAST_RUN_TIMESTAMP.labels(agent_name=self.agent_name).set(
            timestamp or time.time()
        )

    def observe_duration(self, seconds: float) -> None:
        """Record the duration of a run cycle."""
        RUN_DURATION.labels(agent_name=self.agent_name).observe(seconds)

    def duration_timer(self) -> Histogram:
        """Return a context-manager timer for measuring run duration."""
        return RUN_DURATION.labels(agent_name=self.agent_name).time()
